### ISSUE TITLE
UnboundLocalError: local variable 'pretrain_index' referenced before assignment

### ISSUE THREAD

**Issue by tiancpeng** [summitgao/SS-MAE#2]
UnboundLocalError: local variable 'pretrain_index' was referenced before assignment when training.How to solve?

**Comment by Linjyan00** [comment]
This error may have been caused by a negligence during the cleanup phase, which we can stop using “pretrianset” by adding two more if statements "if args. is_pretrain:" or simply removing the "if args.is_pretrain:"  on dataset.py line 109.
